### ISSUE TITLE
Error in prebuildify step windows

### ISSUE THREAD

**Issue by JoranHonig** [tree-sitter/workflows#9]
Hello, I was setting up the publish workflow for tree-sitter-solidity, but am running into this error and I think I'm missing something bc it's erroring on me:

https://github.com/JoranHonig/tree-sitter-solidity/actions/runs/9242464257/job/25427430309

Error msg:
```
gyp ERR! stack TypeError: Cannot destructure property 'libUrl' of 'release[arch]' as it is undefined.
```

This happens in the build x64 step for windows.

**Comment by ObserverOfTime** [comment]
Can you try an older `node-version`?

**Comment by ObserverOfTime** [comment]
That means a node update broke prebuildify, again.
